version: '3.8'

services:
  app:
    image: lucasbx33/gestion-produits-php:v1.0
    container_name: gestion-produits-php
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    environment:
      DB_HOST: db
      DB_NAME: gestion_produits
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - db

  db:
    image: lucasbx33/mysql-gestion-produits:1.0
    container_name: gestion-produits-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_produits
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
